language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

before_install:
  - cat requirements.txt requirements-test.txt > requirements.txt

install: pip install -r requirements.txt
script: python ./manage.py test
